/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuwq_jnicpp_MainActivity */

#ifndef _Included_com_tuwq_jnicpp_MainActivity
#define _Included_com_tuwq_jnicpp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tuwq_jnicpp_MainActivity
 * Method:    hellocpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuwq_jnicpp_MainActivity_hellocpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
